buildscript {
    repositories {
        google()
        mavenCentral() // 替換 jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2' // 更新版本
        classpath 'com.google.gms:google-services:4.3.5'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral() // 替換 jcenter()
        maven { url "https://jitpack.io" }
    }
}

